name: Generate Component Screenshots

on:
  push:
    branches: [ main, master ]
    paths: 
      - 'src/app/country-select/**'
      - 'src/**/*.stories.ts'

jobs:
  screenshots:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Build Storybook
        run: npm run build-storybook

      - name: Serve Storybook
        run: |
          npx http-server storybook-static -p 6006 &
          sleep 10
        
      - name: Generate Screenshots
        run: |
          mkdir -p screenshots
          npx playwright screenshot \
            "http://localhost:6006/iframe.html?args=&id=components-countryselect--default" \
            screenshots/country-select-default.png \
            --viewport-size=400,100
          
          npx playwright screenshot \
            "http://localhost:6006/iframe.html?args=&id=components-countryselect--pre-selected" \
            screenshots/country-select-selected.png \
            --viewport-size=400,100
            
          npx playwright screenshot \
            "http://localhost:6006/iframe.html?args=&id=components-countryselect--all-sizes" \
            screenshots/country-select-sizes.png \
            --viewport-size=400,300
            
          npx playwright screenshot \
            "http://localhost:6006/iframe.html?args=&id=components-countryselect--disabled" \
            screenshots/country-select-disabled.png \
            --viewport-size=400,100

      - name: Commit Screenshots
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add screenshots/
          git diff --staged --quiet || git commit -m "Update component screenshots [skip ci]"
          git push